name = "playreport-avatar-upload"
main = "index.js"
compatibility_date = "2024-10-01"

kv_namespaces = [
  { binding = "BRAND_IMG", id = "83f50e5b059f49af9c3c3315f68dd6a2" }
]

[assets]
directory = "."
binding = "ASSETS"
